const d = {
  Sundari:                  { gender: "матаджі", id: "Sundari", name: "Сундарі" },
  Rasalika:                 { gender: "матаджі", id: "Rasalika", name: "Расаліка" },
  Kinkari:                  { gender: "матаджі", id: "Kinkari", name: "Кінкарі" },
  Gandhari:                 { gender: "матаджі", id: "Gandhari", name: "Ґандгарі" },
  YuvatiRasarani:           { gender: "матаджі", id: "YuvatiRasarani", name: "Юваті Расарані" },
  IrenGuzan:                { gender: "матаджі", id: "IrenGuzan", name: "Ірен Гузан" },
  VisakhaSundari:           { gender: "матаджі", id: "VisakhaSundari", name: "Вішакха Сундарі" },
  Ragini:                   { gender: "матаджі", id: "Ragini", name: "Раґіні" },
  IndulekhaGopi:            { gender: "матаджі", id: "IndulekhaGopi", name: "Індулекха Ґопі" },
  YaninaMelnik:             { gender: "матаджі", id: "YaninaMelnik", name: "Яніна Мельник" },
  ElenaTryndyk:             { gender: "матаджі", id: "ElenaTryndyk", name: "Олена Триндик" },
  MadhuriNayika:            { gender: "матаджі", id: "MadhuriNayika", name: "Мадхурі Наїка" },
  LilaManjari:              { gender: "матаджі", id: "LilaManjari", name: "Ліла Манджарі" },
  GaurangiLila:             { gender: "матаджі", id: "GaurangiLila", name: "Ґауранґі Ліла" },
  YuliaLomaka:              { gender: "матаджі", id: "YuliaLomaka", name: "Юлія Ломака" },
  YuliaStepanyuk:           { gender: "матаджі", id: "YuliaStepanyuk", name: "Юлія Степанюк" },
  AcyutaSakhi:              { gender: "матаджі", id: "AcyutaSakhi", name: "Ач'юта Сакхі" },
  LiliyaHohryakova:         { gender: "матаджі", id: "LiliyaHohryakova", name: "Лілія Хохрякова" },
  LiliyaMishonova:          { gender: "матаджі", id: "LiliyaMishonova", name: "Лілія Мішонова" },
  ViktoriyaSkakun:          { gender: "матаджі", id: "ViktoriyaSkakun", name: "Вікторія Скакун" },
  Tatyana:                  { gender: "матаджі", id: "Tatyana", name: "Тетяна" }, // Узнать у м. Ювати Расарани
  YuliyaBerezkina:          { gender: "матаджі", id: "YuliyaBerezkina", name: "Юлія Березкіна" },
  SvetlanaLetova:           { gender: "матаджі", id: "SvetlanaLetova", name: "Світлана Лєтова" },
  YuliyaMolotkova:          { gender: "матаджі", id: "YuliyaMolotkova", name: "Юлія Молоткова" },
  AnastasiyaSkorobagata:    { gender: "матаджі", id: "AnastasiyaSkorobagata", name: "Анастасія Скоробагата" },
  NikundzhaGopika:          { gender: "матаджі", id: "NikundzhaGopika", name: "Нікунджа Ґопіка" },
  MariyaSazonova:           { gender: "матаджі", id: "MariyaSazonova", name: "Марія Сазонова" },
  TariniKishori:            { gender: "матаджі", id: "TariniKishori", name: "Таріні Кішорі" },
  IrinaZhukovich:           { gender: "матаджі", id: "IrinaZhukovich", name: "Ірина Жукович" },
  Vadzhayantimala:          { gender: "матаджі", id: "Vadzhayantimala", name: "Вайджаянті Мала" },
  ViktoriyaGida:            { gender: "матаджі", id: "ViktoriyaGida", name: "Вікторія Гида" },
  TatyanaCherevatenko:      { gender: "матаджі", id: "TatyanaCherevatenko", name: "Тетяна Череватенко" },
  EkeshvariRadha:           { gender: "матаджі", id: "EkeshvariRadha", name: "Екешварі Радга" },
  NataliyaGavelovskaya:     { gender: "матаджі", id: "NataliyaGavelovskaya", name: "Наталля Гавеловська" },
  NataliyaVyunkovskaya:     { gender: "матаджі", id: "NataliyaVyunkovskaya", name: "Наталля В'юнсковська" },
  AnastasiyaPerezdriyenko:  { gender: "матаджі", id: "AnastasiyaPerezdriyenko", name: "Анастасія Перездрієнко" },
  Sarvadevata:              { gender: "матаджі", id: "Sarvadevata", name: "Сарвадевата" },
  VrajaLila:                { gender: "матаджі", id: "VrajaLila", name: "Враджа Ліла" },
  YashodaGopi:              { gender: "матаджі", id: "YashodaGopi", name: "Яшода-ґопі" },
  SitaSundarangi:           { gender: "матаджі", id: "SitaSundarangi", name: "Сіта Сундаранґі" },
  SanjivaniRasa:            { gender: "матаджі", id: "SanjivaniRasa", name: "Сандживані Раса" },
  JayaSri:                  { gender: "матаджі", id: "JayaSri", name: "Джая Шрі" },
  PremaLata:                { gender: "матаджі", id: "PremaLata", name: "Према Лата" },
  RasikaKumari:             { gender: "матаджі", id: "RasikaKumari", name: "Расіка Кумарі" },
  SanketKunja:              { gender: "матаджі", id: "SanketKunja", name: "Санкет Кунджа" },
  NavinaRadha:              { gender: "матаджі", id: "NavinaRadha", name: "Навіна Радга" },
  NaradiGopi:               { gender: "матаджі", id: "NaradiGopi", name: "Нараді Ґопі" },
  Taravali:                 { gender: "матаджі", id: "Taravali", name: "Таравалі" },
  VrajaGopi:                { gender: "матаджі", id: "VrajaGopi", name: "Враджа-ґопі" },
  AnangaKishori:            { gender: "матаджі", id: "AnangaKishori", name: "Ананґа Кішорі" },
  IshvariLila:              { gender: "матаджі", id: "IshvariLila", name: "Ішварі-ліла" },
  MahaLila:                 { gender: "матаджі", id: "MahaLila", name: "Маха-ліла" },
  LilavatiMadhavi:          { gender: "матаджі", id: "LilavatiMadhavi", name: "Лілаваті Мадгаві" },
  Chandravali:              { gender: "матаджі", id: "Chandravali", name: "Чандравалі" },
  JayaBhadra:               { gender: "матаджі", id: "JayaBhadra", name: "Джая Бгадра" },
  VenuRati:                 { gender: "матаджі", id: "VenuRati", name: "Вену-раті" },
  KalindiMayi:              { gender: "матаджі", id: "KalindiMayi", name: "Калінді-майї" },
  NityanandiniRadha:        { gender: "матаджі", id: "NityanandiniRadha", name: "Ніт'янандіні Радга" },
  RasaLila:                 { gender: "матаджі", id: "RasaLila", name: "Раса-ліла" },
  JayaGopaliSundari:        { gender: "матаджі", id: "JayaGopaliSundari", name: "Джая Ґопалі Сундарі" },
  GovindaDasi:              { gender: "матаджі", id: "GovindaDasi", name: "Ґовінда Дасі" },
  ShyamaKumari:             { gender: "матаджі", id: "ShyamaKumari", name: "Ш'яма Кумарі" },
  LileshvariGaurangi:       { gender: "матаджі", id: "LileshvariGaurangi", name: "Лілешварі Ґауранґі" },
  OlgaStremidlovska:        { gender: "матаджі", id: "OlgaStremidlovska", name: "Ольга Стремідловська" },
  ElenaMurashova:           { gender: "матаджі", id: "ElenaMurashova", name: "Олена Мурашова" },
  MarinaKoltsova:           { gender: "матаджі", id: "MarinaKoltsova", name: "Марина Кольцова" },
  KseniyaPerezdrienko:      { gender: "матаджі", id: "KseniyaPerezdrienko", name: "Ксенія Перездрієнко" }, // Ґґї
  ViktoriyaPolovnaya:       { gender: "матаджі", id: "ViktoriyaPolovnaya", name: "Вкторія Половна" }, // Ґґї
  MitravindaPremika:        { gender: "матаджі", id: "MitravindaPremika", name: "Мітравінда Преміка" },
  NataliyaSikirinskaya:     { gender: "матаджі", id: "NataliyaSikirinskaya", name: "Наталля Сікіринська" },
  MaharaniSeva:             { gender: "матаджі", id: "MaharaniSeva", name: "Махарані Сева" },
  Chitravasini:             { gender: "матаджі", id: "Chitravasini", name: "Читравасіні" },
  MadhaviPriti:             { gender: "матаджі", id: "MadhaviPriti", name: "Мадгаві Пріті" },
  KamalaPadma:              { gender: "матаджі", id: "KamalaPadma", name: "Камала Падма" },
  TanuSri:                  { gender: "матаджі", id: "TanuSri", name: "Тану Шрі" },
  MadhuryaRati:             { gender: "матаджі", id: "MadhuryaRati", name: "Мадгур'я Раті" },
  Dzhanaki:                 { gender: "матаджі", id: "Dzhanaki", name: "Джанакі" },
  LilaSmriti:               { gender: "матаджі", id: "LilaSmriti", name: "Ліла Смріті" },
  AnandiniPurna:            { gender: "матаджі", id: "AnandiniPurna", name: "Анандіні Пурна" },
  IrinaAntipenko:           { gender: "матаджі", id: "IrinaAntipenko", name: "Iрина Антипова" },
  ElenaReshetnikova:        { gender: "матаджі", id: "ElenaReshetnikova", name: "Олена Решетнiкова" },
  VasantaLakshmi:           { gender: "матаджі", id: "VasantaLakshmi", name: "Васанта Лакшмі" },
  LalitaAmbika:             { gender: "матаджі", id: "LalitaAmbika", name: "Лаліта Амбіка" },
  KarolinaFilomonova:       { gender: "матаджі", id: "KarolinaFilomonova", name: "Кароліна Філімонова" },
  TrilokiniLalita:          { gender: "матаджі", id: "TrilokiniLalita", name: "Трілокіні Лаліта" },
  NirmalaGayatri:           { gender: "матаджі", id: "NirmalaGayatri", name: "Нірмала Ґаятрі" },
  Alisa:                    { gender: "матаджі", id: "Alisa", name: "Аліса" },
  NandaYashoda:             { gender: "матаджі", id: "NandaYashoda", name: "Нанда-Яшода" },
  VarshanaRadhe:            { gender: "матаджі", id: "VarshanaRadhe", name: "Варшана Радге" },
  KhrystynaLisogor:         { gender: "матаджі", id: "KhrystynaLisogor", name: "Христина Лісогор" },
  AnandiniKrishnaa:         { gender: "матаджі", id: "AnandiniKrishnaa", name: "Анандіні Крішнаа" },
  TapatiGaurangi:           { gender: "матаджі", id: "TapatiGaurangi", name: "Тапаті Ґауранґі" },
  LanganaKshama:            { gender: "матаджі", id: "LanganaKshama", name: "Ланґана Кшама" },
  VrindaPriya:              { gender: "матаджі", id: "VrindaPriya", name: "Врiнда Прiя" },
  Larisa:                   { gender: "матаджі", id: "Larisa", name: "Лариса" },
  Alina:                    { gender: "матаджі", id: "Alina", name: "Алiна" },
  Anna:                     { gender: "матаджі", id: "Anna", name: "Анна" },
  
  ShyamaLila:               { gender: "прабгу", id: "ShyamaLila", name: "Ш'яма Ліла" },
  IvanChamkin:              { gender: "прабгу", id: "IvanChamkin", name: "Іван Чамкін" },
  VitaliyBabenko:           { gender: "прабгу", id: "VitaliyBabenko", name: "Віталій Бабенко" },
  Mahadyuti:                { gender: "прабгу", id: "Mahadyuti", name: "Махад'юті" },
  AleksandrFedorina:        { gender: "прабгу", id: "AleksandrFedorina", name: "Олександр Федорина" },
  IgorPerezdrienko:         { gender: "прабгу", id: "IgorPerezdrienko", name: "Ігор Перездрієнко" },
  KirillStepanyuk:          { gender: "прабгу", id: "KirillStepanyuk", name: "Кирило Степанюк" },
  Harinamanrita:            { gender: "прабгу", id: "Harinamanrita", name: "Харінамамріта" },
  RamaRupa:                 { gender: "прабгу", id: "RamaRupa", name: "Рама Рупа" },
  ArchaVigraha:             { gender: "прабгу", id: "ArchaVigraha", name: "Арча Віґраха" },
  TulasiValabha:            { gender: "прабгу", id: "TulasiValabha", name: "Туласі Валабга" },
  RasaSagara:               { gender: "прабгу", id: "RasaSagara", name: "Раса Саґара" },
  TushtaKrishna:            { gender: "прабгу", id: "TushtaKrishna", name: "Тушта Крішна" },
  SudhaKantha:              { gender: "прабгу", id: "SudhaKantha", name: "Судга Кантха" },
  YashodaKumar:             { gender: "прабгу", id: "YashodaKumar", name: "Яшода Кумар" },
  RamVijay:                 { gender: "прабгу", id: "RamVijay", name: "Рам-Віджай" },
  Yogeshvara:               { gender: "прабгу", id: "Yogeshvara", name: "Йоґешвара" },
  AnupamGovinda:            { gender: "прабгу", id: "AnupamGovinda", name: "Анупам Ґовінда" },
  Vrindaranya:              { gender: "прабгу", id: "Vrindaranya", name: "Вріндаран'я" },
  VrajaBhakti:              { gender: "прабгу", id: "VrajaBhakti", name: "Враджа-Бгакті" },
  DhruvaMaharaj:            { gender: "прабгу", id: "DhruvaMaharaj", name: "Дгрува Махарадж" },
  AnantaVasudev:            { gender: "прабгу", id: "AnantaVasudev", name: "Ананта Васудев" },
  IshvaraChaytanya:         { gender: "прабгу", id: "IshvaraChaytanya", name: "Ішвара Чайтан'я" },
  Madhukari:                { gender: "прабгу", id: "Madhukari", name: "Мадгукарі" },
  RasikaKumar:              { gender: "прабгу", id: "RasikaKumar", name: "Расіка Кумар" },
  MaksimDatsenko:           { gender: "прабгу", id: "MaksimDatsenko", name: "Максим Даценко" },
  VanamaliGovinda:          { gender: "прабгу", id: "VanamaliGovinda", name: "Ванамалі Ґовінда" },
  IgorMorozov:              { gender: "прабгу", id: "IgorMorozov", name: "Ігор Морозов" },
  MihailDerkach:            { gender: "прабгу", id: "MihailDerkach", name: "Михайло Деркач" },
  OlegKalinovskiy:          { gender: "прабгу", id: "OlegKalinovskiy", name: "Олег Калиновський" },
  MaksimSteshenko:          { gender: "прабгу", id: "MaksimSteshenko", name: "Максим Стешенко" },
  AntonKrivokorytov:        { gender: "прабгу", id: "AntonKrivokorytov", name: "Антон Кривокоритов" },
  Lochana:                  { gender: "прабгу", id: "Lochana", name: "Лочана" },
  NitayGaurachandra:        { gender: "прабгу", id: "NitayGaurachandra", name: "Нітай Ґаурачандра" },
  VedantaChaitanya:         { gender: "прабгу", id: "VedantaChaitanya", name: "Веданта Чайтан'я" },
  YuriyVarava:              { gender: "прабгу", id: "YuriyVarava", name: "Юрій Варава" },
  IlyaVasilchenko:          { gender: "прабгу", id: "IlyaVasilchenko", name: "Ілля Васильченко" },
  SadhuSeva:                { gender: "прабгу", id: "SadhuSeva", name: "Садгу Сева" },
  AnatoliyMotsygailo:       { gender: "прабгу", id: "AnatoliyMotsygailo", name: "Анатолій Моцигайло" },
  EvgeniyBayruk:            { gender: "прабгу", id: "EvgeniyBayruk", name: "Євгеній Байрук" },
  MukundaGauranga:          { gender: "прабгу", id: "MukundaGauranga", name: "Мукунда Ґауранґа" },
  IveshvaraGopal:           { gender: "прабгу", id: "IveshvaraGopal", name: "Івешвара Ґопал" },
  ZaboraBogdan:             { gender: "прабгу", id: "ZaboraBogdan", name: "Богдан Забора" },
  Damodara:                 { gender: "прабгу", id: "Damodara", name: "Дамодара" },
  Hanuman:                  { gender: "прабгу", id: "Hanuman", name: "Хануман" },
  VladislavEmets:           { gender: "прабгу", id: "VladislavEmets", name: "Владислав Ємець" },
  DmitriyRubets:            { gender: "прабгу", id: "DmitriyRubets", name: "Дмитро Рубець" },
  DmitriyZinchenko:         { gender: "прабгу", id: "DmitriyZinchenko", name: "Дмитро Зiнченко" },
  RasaVarshi:               { gender: "прабгу", id: "RasaVarshi", name: "Раса-варші" },
  DamodarKumar:             { gender: "прабгу", id: "DamodarKumar", name: "Дамодар Кумар" },
  MadhyaPandava:            { gender: "прабгу", id: "MadhyaPandava", name: "Мадг'я  Пандава" },
};